environment:
  matrix:
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38-x64

init:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - SET PYTHONIOENCODING=utf-8

install:
  - python -m pip install --no-cache-dir  -r requirements.txt
  - python -m pip install --no-cache-dir  -r dev-requirements.txt

build: false

test_script:
  - make lint
  - make test

branches:
  only:
    - master

cache:
  - '%LOCALAPPDATA%\pip\Cache'
