os: linux
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - nightly

matrix:
  allow_failures:
    - python: nightly
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - make lint

script:
  - make test

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master

notifications:
  email: false
